blank_issues_enabled: true
contact_links:
  - name: Questions and discussion
    url: https://github.com/thesharkartist/shark-artist-great-white-theme/discussions
    about: Please use discussions for general questions.
